spring:
  datasource:
    url: jdbc:mysql://192.168.200.100:3306/lease
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

#用于打印框架生成的sql语句，便于调试
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: not_empty

  type-aliases-package: com.atguigu.lease.model.entity


minio:
  endpoint: http://192.168.200.100:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: lease
springdoc:
  default-flat-param-object: true